### ISSUE TITLE
Error Processing Library

### ISSUE THREAD

**Issue by djgreig** [Josh5/docker-libraryoptimise#5]
Trying to process a part of my library. Getting this sort of error with different files. I have turned debugging on.

INFO:root:LibraryOptimiser - Processing files in '/library/'
INFO:root:LibraryOptimiser - Starting ScheduledTask
INFO:root:LibraryOptimiser - Starting EventProcessor
INFO:root:LibraryOptimiser - Running scheduled task
INFO:root:LibraryOptimiser - /library/
INFO:root:LibraryOptimiser - []
INFO:root:LibraryOptimiser - [
"Beauty and the Beast (2017).mkv",
"poster.jpg"
]
INFO:root:LibraryOptimiser - Checking file /library/Beauty and the Beast (2017)/Beauty and the Beast (2017).mkv
Traceback (most recent call last):
File "/optimiser", line 498, in <module>
main()
File "/optimiser", line 484, in main
wm.add_watch(LIBRARY_PATH, pyinotify.ALL_EVENTS, rec=True)
File "/usr/local/lib/python3.5/dist-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 1916, in add_watch
File "/usr/local/lib/python3.5/dist-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 1833, in __add_watch
File "/usr/local/lib/python3.5/dist-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 153, in inotify_add_watch
File "/usr/local/lib/python3.5/dist-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 246, in _inotify_add_watch
UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-14: ordinal not in range(128)

**Comment by Josh5** [comment]
This project has now been discontinued and moved to https://github.com/Josh5/unmanic
Unmanic is a complete re-write of the optimiser service that ran in this docker image.

That being said, this looks like an issue with pyinotify so I doubt it is resolved in Unmanic. As such I have moved this issue over to the new project:
https://github.com/Josh5/unmanic/issues/1

I will close this issue off here as I will not be carrying out any further development on the docker-libraryoptimise project


Thanks
